// Code generated by MockGen. DO NOT EDIT.
// Source: time_manager.go

// Package mock_time_manager is a generated GoMock package.
package mock_time_manager

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimeManager is a mock of TimeManager interface.
type MockTimeManager struct {
	ctrl     *gomock.Controller
	recorder *MockTimeManagerMockRecorder
}

// MockTimeManagerMockRecorder is the mock recorder for MockTimeManager.
type MockTimeManagerMockRecorder struct {
	mock *MockTimeManager
}

// NewMockTimeManager creates a new mock instance.
func NewMockTimeManager(ctrl *gomock.Controller) *MockTimeManager {
	mock := &MockTimeManager{ctrl: ctrl}
	mock.recorder = &MockTimeManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeManager) EXPECT() *MockTimeManagerMockRecorder {
	return m.recorder
}

// MillisecondsToTime mocks base method.
func (m_2 *MockTimeManager) MillisecondsToTime(m int64) time.Time {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MillisecondsToTime", m)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// MillisecondsToTime indicates an expected call of MillisecondsToTime.
func (mr *MockTimeManagerMockRecorder) MillisecondsToTime(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MillisecondsToTime", reflect.TypeOf((*MockTimeManager)(nil).MillisecondsToTime), m)
}

// Now mocks base method.
func (m *MockTimeManager) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeManagerMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeManager)(nil).Now))
}
