// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CareerResponse career response
//
// swagger:model CareerResponse
type CareerResponse struct {

	// bonus money
	// Example: 15%
	BonusMoney string `json:"bonus_money,omitempty"`

	// employee since
	// Example: 20.04.2024
	EmployeeSince string `json:"employee_since,omitempty"`

	// full rate
	// Example: 100000
	FullRate int64 `json:"full_rate,omitempty"`

	// post
	// Example: Фронтендер
	Post string `json:"post,omitempty"`

	// total points
	TotalPoints int64 `json:"total_points,omitempty"`

	// vocation
	Vocation int64 `json:"vocation,omitempty"`
}

// Validate validates this career response
func (m *CareerResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this career response based on context it is used
func (m *CareerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CareerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CareerResponse) UnmarshalBinary(b []byte) error {
	var res CareerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
