// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangePasswordResponse change password response
//
// swagger:model ChangePasswordResponse
type ChangePasswordResponse struct {

	// code
	// Example: 200
	Code int64 `json:"code,omitempty"`

	// detail
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: Password successfully changed
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Пароль успешно изменен
	Message string `json:"message,omitempty"`
}

// Validate validates this change password response
func (m *ChangePasswordResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this change password response based on context it is used
func (m *ChangePasswordResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangePasswordResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangePasswordResponse) UnmarshalBinary(b []byte) error {
	var res ChangePasswordResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
