// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangePassRequest change pass request
//
// swagger:model ChangePassRequest
type ChangePassRequest struct {

	// login
	// Example: Lev
	Login string `json:"login,omitempty"`

	// new pass
	// Example: 1377
	NewPass string `json:"new_pass,omitempty"`

	// old pass
	// Example: 1337
	OldPass string `json:"old_pass,omitempty"`
}

// Validate validates this change pass request
func (m *ChangePassRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this change pass request based on context it is used
func (m *ChangePassRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangePassRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangePassRequest) UnmarshalBinary(b []byte) error {
	var res ChangePassRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
