// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExtendData extend data
//
// swagger:model ExtendData
type ExtendData struct {

	// key
	// Example: Адресная премия (математика)
	Key string `json:"key,omitempty"`

	// tooltip
	// Example: Премия выданная за особые заслуги перед матаном
	Tooltip string `json:"tooltip,omitempty"`

	// value
	// Example: 10000
	Value string `json:"value,omitempty"`
}

// Validate validates this extend data
func (m *ExtendData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this extend data based on context it is used
func (m *ExtendData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExtendData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtendData) UnmarshalBinary(b []byte) error {
	var res ExtendData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
