// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetReviewRequest get review request
//
// swagger:model GetReviewRequest
type GetReviewRequest struct {

	// month
	Month string `json:"month,omitempty"`

	// year
	Year string `json:"year,omitempty"`
}

// Validate validates this get review request
func (m *GetReviewRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get review request based on context it is used
func (m *GetReviewRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetReviewRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetReviewRequest) UnmarshalBinary(b []byte) error {
	var res GetReviewRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
