// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogInResponse log in response
//
// swagger:model LogInResponse
type LogInResponse struct {

	// code
	// Example: 200
	Code int64 `json:"code,omitempty"`

	// detail
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: Successfully auth
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Успешная авторизация
	Message string `json:"message,omitempty"`
}

// Validate validates this log in response
func (m *LogInResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log in response based on context it is used
func (m *LogInResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogInResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogInResponse) UnmarshalBinary(b []byte) error {
	var res LogInResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
