// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogInRequest log in request
//
// swagger:model LogInRequest
type LogInRequest struct {

	// login
	// Example: Lev
	Login string `json:"login,omitempty"`

	// password
	// Example: 1337
	Password string `json:"password,omitempty"`
}

// Validate validates this log in request
func (m *LogInRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log in request based on context it is used
func (m *LogInRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogInRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogInRequest) UnmarshalBinary(b []byte) error {
	var res LogInRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
