// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PersonalAcc personal acc
//
// swagger:model PersonalAcc
type PersonalAcc struct {

	// user id
	// Example: 123
	UserID string `json:"user_id,omitempty"`

	// username
	// Example: user123
	Username string `json:"username,omitempty"`
}

// Validate validates this personal acc
func (m *PersonalAcc) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this personal acc based on context it is used
func (m *PersonalAcc) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PersonalAcc) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PersonalAcc) UnmarshalBinary(b []byte) error {
	var res PersonalAcc
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
