// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Points points
//
// swagger:model Points
type Points struct {

	// The percentage of the points, e.g., '15%'
	// Example: 15%
	Percent string `json:"percent,omitempty"`

	// The value of the points
	// Example: 10000
	Value int64 `json:"value,omitempty"`
}

// Validate validates this points
func (m *Points) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this points based on context it is used
func (m *Points) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Points) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Points) UnmarshalBinary(b []byte) error {
	var res Points
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
