// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SamePasswordResponse same password response
//
// swagger:model SamePasswordResponse
type SamePasswordResponse struct {

	// code
	// Example: 400
	Code int64 `json:"code,omitempty"`

	// detail
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: Passwords must be different
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Пароли не должны совпадать
	Message string `json:"message,omitempty"`
}

// Validate validates this same password response
func (m *SamePasswordResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this same password response based on context it is used
func (m *SamePasswordResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SamePasswordResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SamePasswordResponse) UnmarshalBinary(b []byte) error {
	var res SamePasswordResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
