// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UnauthorizedTokenResponse unauthorized token response
//
// swagger:model UnauthorizedTokenResponse
type UnauthorizedTokenResponse struct {

	// code
	// Example: 401
	Code int64 `json:"code,omitempty"`

	// detail
	// Example: invalid token claims
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: Invalid token
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Недействительный токен
	Message string `json:"message,omitempty"`
}

// Validate validates this unauthorized token response
func (m *UnauthorizedTokenResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this unauthorized token response based on context it is used
func (m *UnauthorizedTokenResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UnauthorizedTokenResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnauthorizedTokenResponse) UnmarshalBinary(b []byte) error {
	var res UnauthorizedTokenResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
