// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UnauthorizedResponse unauthorized response
//
// swagger:model UnauthorizedResponse
type UnauthorizedResponse struct {

	// code
	// Example: 401
	Code int64 `json:"code,omitempty"`

	// detail
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: Wrong login or password
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Неверный логин или пароль
	Message string `json:"message,omitempty"`
}

// Validate validates this unauthorized response
func (m *UnauthorizedResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this unauthorized response based on context it is used
func (m *UnauthorizedResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UnauthorizedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnauthorizedResponse) UnmarshalBinary(b []byte) error {
	var res UnauthorizedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
