// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserNotFoundResponse user not found response
//
// swagger:model UserNotFoundResponse
type UserNotFoundResponse struct {

	// code
	// Example: 400
	Code int64 `json:"code,omitempty"`

	// detail
	// Example: user not found
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: User not found, incorrect ID
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Пользователь не найден, неверный ID
	Message string `json:"message,omitempty"`
}

// Validate validates this user not found response
func (m *UserNotFoundResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user not found response based on context it is used
func (m *UserNotFoundResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserNotFoundResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserNotFoundResponse) UnmarshalBinary(b []byte) error {
	var res UserNotFoundResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
