// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidationErrorResponse validation error response
//
// swagger:model ValidationErrorResponse
type ValidationErrorResponse struct {

	// code
	// Example: 400
	Code int64 `json:"code,omitempty"`

	// detail
	// Example: QueryParseError
	Detail string `json:"detail,omitempty"`

	// en message
	// Example: Validation failed. Please, contact support
	EnMessage string `json:"en_message,omitempty"`

	// message
	// Example: Ошибка валидации запроса. Пожалуйста, обратитесь в поддержку
	Message string `json:"message,omitempty"`
}

// Validate validates this validation error response
func (m *ValidationErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this validation error response based on context it is used
func (m *ValidationErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidationErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidationErrorResponse) UnmarshalBinary(b []byte) error {
	var res ValidationErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
