// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VocationResponse vocation response
//
// swagger:model VocationResponse
type VocationResponse struct {

	// Количество дней отпуска
	Value int64 `json:"Value,omitempty"`
}

// Validate validates this vocation response
func (m *VocationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vocation response based on context it is used
func (m *VocationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VocationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VocationResponse) UnmarshalBinary(b []byte) error {
	var res VocationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
